### ISSUE TITLE
Argonaut being too lenient when nested option parsing fails

### ISSUE THREAD

**Issue by stoyle** [argonaut-io/argonaut#212] opened 2016-02-13 11:36 UTC
Hi guys, wanted to report an issue we encountered in prod (ish...).
Argonaut accepts incorrect nested types as None, when it does not parse correctly. Created a test case for this: (https://github.com/stoyle/argonaut/commit/8cd08cef65a23666955456f1e9225df999743153). The failing case at line 34.

Is this by design, or is it a bug? I guess fixing it is a breaking change in argonaut, but I would personally want behavior on always, fail fast etc. Is there a way it could be optionally enabled up? 

I wouldn't min trying to submit a patch for this, if you give me pointers on how to add such a change.

And thanks for argonaut, great library! Cheers,
Alf

**Comment by lvicentesanchez** [comment] 2016-02-13 11:53
That's interesting, I will take a look to the Option encoder/decoder. If it's not by design but a bug, it's going to be an interesting one to fix as some people might rely on that behaviour @seanparsons

**Comment by seanparsons** [comment] 2016-02-13 11:53
I'm inclined to agree with you that an incompatible decode should fail rather than succeed "invisibly".

Looking at the commits it could well be an unintentional side effect of other work. If people rely on that behaviour it might just be that they'll have to deal with it as it breaks the principle of least surprise.

If you want to submit a patch, I'll be totally happy to accommodate that (that test above would also be great to incorporate as well), you'll be wanting to look in DecodeJson.scala for the appropriate instance in there.

**Comment by stoyle** [comment] 2016-02-13 12:55
Ok great. I'll try to create a patch as soon as possible, probably next week.

**Comment by stoyle** [comment] 2016-02-14 16:55
So apparently https://github.com/stoyle/argonaut/commit/3c7a21c2e09016cd6f437efa3d1c1fd8a8e0880a fixed the problem, all tests run successfully.

I rewrote it using Either, since I thought it was more straight forward than the fold, which would have been:
```  def option: DecodeResult[Option[A]] =
    result.fold(
      { case (s, h) => DecodeResult.fail(s, h) },
      a => DecodeResult.ok(Some(a))
    )```

However, going back in history, seems it has been this way forever. It was basically the same code when it was added in 5213a568278dd7145c099eb8f2602a7b1d2d1842.

Seems very intentional to succeed the None-case, but there are no test covering it, and I am personally not sure when this behavior is desirable.

Is this a fix you guys want into argonaut? Or should it be fixed in any other way?

**Comment by seanparsons** [comment] 2016-02-14 23:56
I think it should be fixed this way, it would be better to support the other use case by decoding to an ADT that is either the "optional" thing or Json.

**Comment by stoyle** [comment] 2016-02-15 07:03
Ok. Added a PR. Let me know if you want anything changed.

Cheers,
Alf

**Comment by seanparsons** [comment] 2016-02-15 14:02
This should be good now that the PR has been merged.

**Closed by seanparsons** 2016-02-15 14:02 UTC
